### ISSUE TITLE
Use tracer instead of child span

### ISSUE THREAD

**Issue by treyhyde** [kamon-io/kamon-jdbc#31]
In examples such as https://github.com/jaegertracing/jaeger-ui/blob/master/media/ss_trace.png, it's much more clear what is external calls vs internal activity.  The Jaeger Hotrod Example app in this illustration creates new tracers to call these out.   At a glace, this is significantly easier to read in the Jaeger UI than the child span approach that kamon-jdbc takes.  It also probably plays better when looking at dependency graphs, etc.

**Comment by ivantopo** [comment]
Hey @treyhyde, just to be sure I understand:

Are you suggesting that the readability of traces could be improved if the JDBC spans reported as part of a "postgres" service instead of the "local" service?

If that is the case, it certainly improves readability of the trace but this change is not something we can do on the JDBC instrumentation itself because Kamon doesn't have the notion of separate tracers nor separate services within the same process. I just had a quick look at the Jaeger reporter and it looks like we could hack it there by creating a new client for each database and send the Spans separately.

You can follow up the possible changes to the Jaeger reporter on this issue: https://github.com/kamon-io/kamon-jaeger/issues/14
